### ISSUE TITLE
Any code for downloading the dataset?

### ISSUE THREAD

**Issue by wangxinyu0922** [google-research-datasets/conceptual-captions#1]
Thank you for your great work.
Can you provide any example code for download images by urls from the tsv files? Some url can not be downloaded by urllib in python (IOError: [Errno socket error] [Errno 110] Connection timed out). But I can see the images in the browser.

**Comment by dingnan-google** [comment]
Thank you for your interest! Unfortunately, we cannot provide the code for downloading images by urls from the tsv files because of copyright/legal issues.
