### ISSUE TITLE
Download of the dataset is not working

### ISSUE THREAD

**Issue by ggaemo** [google-research-datasets/conceptual-captions#10]
Hello is the link for the training split of the dataset operating? I am in South Korea and it is not working

**Comment by ggaemo** [comment]
Never Mind, I kept on clicking and it worked eventually

**Comment by nilinykh** [comment]
What did you mean by 'kept clicking on it and it worked'?
I am experiencing the same problem - cannot download the dataset. Is there a way to get the dataset somehow?
