### ISSUE TITLE
Conceptual Captions Dataset with Proper Names

### ISSUE THREAD

**Issue by g-luo** [google-research-datasets/conceptual-captions#11]
I was wondering if there was a version of the Conceptual Captions Dataset without the proper names cleaned out (ie the version of the dataset with captions like (“Crowd at a concert in Los Angeles“) and (“Former Miss World Priyanka Chopra on the red carpet"))? 

Thanks!

**Comment by sharma-piyush** [comment]
The original alt-texts are not available.
